import {
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFolder,
  faArrowAltCircleDown,
  faCheckCircle,
  faCopy,
  faEnvelope,
  faFlag,
  faTrashAlt,
} from '@fortawesome/free-regular-svg-icons'
import {
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faBook,
  faCheck,
  faChevronCircleDown,
  faChevronDown,
  faCloud,
  faDownload,
  faExclamationCircle,
  faExclamationTriangle,
  faFileDownload,
  faHome,
  faKey,
  faLanguage,
  faLink,
  faMinus,
  faMusic,
  faPen,
  faPlus,
  faSearch,
  faSignOutAlt,
  faTh,
  faThLarge,
  faThList,
  faUndo,
  faCopy as faCopySolid,
  faExternalLinkAlt,
} from '@fortawesome/free-solid-svg-icons'
import * as Icons from '@fortawesome/free-brands-svg-icons'

// Require had to be used to prevent SSR failure in Next.js
// Related discussion: https://github.com/FortAwesome/Font-Awesome/issues/19348
const { library, config } = require('@fortawesome/fontawesome-svg-core')
config.autoAddCss = false

const iconList = Object.keys(Icons)
  .filter(k => k !== 'fab' && k !== 'prefix')
  .map(icon => Icons[icon])

library.add(
  faFileImage,
  faFilePdf,
  faFileWord,
  faFilePowerpoint,
  faFileExcel,
  faFileAudio,
  faFileVideo,
  faFileArchive,
  faFileCode,
  faFileAlt,
  faFile,
  faFlag,
  faFolder,
  faMusic,
  faArrowLeft,
  faArrowRight,
  faAngleRight,
  faFileDownload,
  faCopy,
  faCopySolid,
  faPlus,
  faMinus,
  faDownload,
  faLink,
  faUndo,
  faBook,
  faArrowAltCircleDown,
  faKey,
  faTrashAlt,
  faSignOutAlt,
  faEnvelope,
  faCloud,
  faChevronCircleDown,
  faExternalLinkAlt,
  faExclamationCircle,
  faExclamationTriangle,
  faHome,
  faCheck,
  faCheckCircle,
  faSearch,
  faChevronDown,
  faTh,
  faThLarge,
  faThList,
  faLanguage,
  faPen,
  ...iconList
)
